# This is a basic workflow to help you get started with Actions

name: Build and package RoBERTa-sequencing to Dockerhub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: download model
        run: wget https://media.githubusercontent.com/media/onnx/models/master/text/machine_comprehension/roberta/model/roberta-sequence-classification-9.onnx

      - name: copy model to webapp folder
        run: |
          cp ./roberta-sequence-classification-9.onnx ./webapp
          
# #         DOCKER HUB
#       - name: Authenticate to Docker hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
#       - name: build flask-app container
#         uses: docker/build-push-action@v2
#         with:
#           context: ./
#           file: ./Dockerfile
#           push: true
#           tags: alfredodeza/flask-roberta:latest

#       GitHub Container Registry 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY }}

      - name: build flask-app and push to registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ghcr.io/sontt22791/flask-roberta:latest
          push: true
